- hosts: localhost
  remote_user: root
  gather_facts: false
  tags: ansible_hosts
  tasks:
    - name: generate k8s hosts
      template: 
         src: templates/ansible_hosts.j2 
         dest: ../k8s_hosts

- hosts: localhost
  remote_user: root
  gather_facts: false
  vars:
    - mode: new
  roles:
    - ssh_auth
  tags: ssh_auth