---
- name: Generate the SSH script new node
  template: src=add_node_ssh_auth.sh.j2 dest=roles/ssh_auth/generate_files/add_ndoe_ssh_auth.sh mode=0755

- name: Execute the SSH script new node
  shell: cd roles/ssh_auth/generate_files && /bin/bash add_ndoe_ssh_auth.sh