---
- name: Generate the SSH script
  template: src=ssh_auth.sh.j2 dest=roles/ssh_auth/generate_files/ssh_auth.sh mode=0755

- name: Execute the SSH script
  shell: cd roles/ssh_auth/generate_files && /bin/bash ssh_auth.sh